# Generated by Django 3.2 on 2021-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('fundacion', models.IntegerField(help_text='Enter field documentation', max_length=20)),
            ],
        ),
    ]
